### ISSUE TITLE
SKOS validator: Grouping by error type

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#2]
It does not make much sense to display all concepts by default for validation purposes.
Concepts should be grouped by error type and one group for OK.
Each group should display number of elements.

E.g. for https://raw.githubusercontent.com/openbudgets/Code-lists/master/UnifiedViews/skosified/currencies/currency.ttl, everything seems OK, so I should see "No errors" message and number of concepts.

For https://raw.githubusercontent.com/openbudgets/Code-lists/master/UnifiedViews/skosified/cpa/cpa.ttl I should see a group of concepts, that are missing the `skos:inScheme` property.

For each group, one example IRI should be displayed (so that I can go check the data) and display of all concepts in the group should be on demand.

**Comment by jirihelmich** [comment]
![image](https://cloud.githubusercontent.com/assets/174768/13496119/c8a7b892-e14e-11e5-9ee1-1c3be468670e.png)
