### ISSUE TITLE
Validation input

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/visualizations#23]
Allow also URL download and Sparql Endpoint to be an input.

**Comment by jirihelmich** [comment]
Should I reuse the component from homescreen but somehow changed so that it allows only 1 DS at a time?

**Comment by jakubklimek** [comment]
I think that would be optimal.

**Comment by jirihelmich** [comment]
I extracted the homescreen component and related logic and re-used it with DCV validation and SKOS validation.

I tested it, but if you test as well, I will be glad.
