### ISSUE TITLE
Bug with encoding in DCV Viz

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#24]
![image](https://cloud.githubusercontent.com/assets/718827/13498263/7dbf1fcc-e159-11e5-94b7-9722424662e5.png)
[czso-demography.zip](https://github.com/linkedpipes/visualizations/files/157019/czso-demography.zip)

**Comment by jirihelmich** [comment]
Cannot reproduce this. Is it still happening for you?

**Comment by jakubklimek** [comment]
Actually, now when I upload the two files (data and dsd from https://github.com/linkedpipes/visualizations/tree/gh-pages/example), it discovers nothing.
The encoding issue was happening when uploading these files (not referencing them via URL)

**Comment by jirihelmich** [comment]
Locally, it works, including encoding. I just tried again. You might have hit redeploy, I will try in a while after the latest change is deployed.

**Comment by jakubklimek** [comment]
Still discovers nothing...

**Comment by jirihelmich** [comment]
I will check how it behaves with virtuoso on xrg12.
Fri, 4 Mar 2016 v 21:52 odesílatel Jakub Klímek notifications@github.com
napsal:

**Comment by jirihelmich** [comment]
Cannot reproduce anywhere. https://youtu.be/tR5g9BhPxTA

**Comment by jakubklimek** [comment]
Hmm... now it works for me too even though once it froze on "Evaluating pipeline". Nevertheless, no encoding issue anymore.
