### ISSUE TITLE
Hierarchy visualizer - language support

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#25]
- [ ] ability to change language via UI
- [ ] ability to change language via URL

**Comment by jakubklimek** [comment]
When visualizing https://raw.githubusercontent.com/openbudgets/datasets/master/greek-municipalities/codelist/athens-administrations.ttl, I see no label. (the language tags are el)

**Comment by jirihelmich** [comment]
![image](https://cloud.githubusercontent.com/assets/174768/13554617/e526474e-e3ac-11e5-895a-158e2918c58d.png)
