### ISSUE TITLE
DCV: mixed label languages

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#27]
![image](https://cloud.githubusercontent.com/assets/718827/13520511/3a883756-e1e1-11e5-908b-769950fe76a8.png)

Those are labels from dereferencing. Maybe the issue is there?

Related to https://github.com/ldvm/LDVMi/issues/93?

**Comment by jirihelmich** [comment]
The visualizer goes through all the languages (currently cs, en, and no language). Firstly, it shifts the currently selected language to first position. Then it loops through the list of languages and tries to find any label in the given ordering of languages.

Are all the labels present in both en and cs?

**Comment by jakubklimek** [comment]
http://linked.opendata.cz/generated/resource/age/Y0
http://linked.opendata.cz/generated/resource/age/Y1T4

**Comment by jirihelmich** [comment]
Could you provide a source of the data? I tried yesterdays TTL and LOD.cz and it's not there.

**Comment by jakubklimek** [comment]
http://visualization.linkedpipes.com/example/datacube.ttl http://visualization.linkedpipes.com/example/dsd.ttl

**Comment by jirihelmich** [comment]
```
skos:prefLabel  "10-14 let"@cs ,
        "10-14 years"@en ,
        "10-14 years"@cs ;
```

**Comment by jakubklimek** [comment]
Ow... that is the temporary fix... ok, will clear that and try again

**Comment by jirihelmich** [comment]
There's a bug in extraction as well, but this won't make it better...

**Comment by jakubklimek** [comment]
OK, fixed the data (deleted the temporary fix), however, it is still happening.

Moreover, weird thing is happening when switching languages in menu:
Czech:
![image](https://cloud.githubusercontent.com/assets/718827/13534787/2f4c49da-e237-11e5-88d2-cf449fccce2b.png)
English:
![image](https://cloud.githubusercontent.com/assets/718827/13534795/3592ad2a-e237-11e5-89f7-273954f78780.png)

Notice that only 0 and 25-29 changes, and it changes to `skos:notation`, not a label

**Comment by jirihelmich** [comment]
It's queried like this:

```

 SELECT DISTINCT ?l ?spl ?sn ?sna ?st
 WHERE {
     OPTIONAL { <$uri> rdfs:label ?l . }
     OPTIONAL { <$uri> skos:prefLabel ?spl . }
     OPTIONAL { <$uri> skos:notation ?sn . }
     OPTIONAL { <$uri> schema:name ?sna . }
     OPTIONAL { <$uri> schema:title ?st . }
 }
```

And labels are taken in this ordering: sn, l, spl, sna, st and then set to a map, so I think that the priority is actually reversed.

You can choose the expected priority, I will replace it.

**Comment by jakubklimek** [comment]
This does not make sense because it behaves differently for each concept, even though each of the age categories, for example, has both `skos:prefLabel` in Czech and English and `skos:notation`.

As to the priority, it should be ?spl, ?sna, ?l, ?sn, ?dct, ?st where ?dct is `dcterms:title`

**Comment by jirihelmich** [comment]
Extractor rewritten. It previously took just the first result from the result set, which was basically the randomization. Now it assembles the whole labels table and chooses the most suitable one.

**Comment by jakubklimek** [comment]
The priorities are not correct. For regions from ruian, ?sn is displayed instead of ?sna.
![image](https://cloud.githubusercontent.com/assets/718827/13539701/45272584-e252-11e5-92bf-f3cfe979cc8d.png)
