### ISSUE TITLE
SKOS validator: Root scheme -> root concept?

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#3]
In SKOS validator, using https://raw.githubusercontent.com/openbudgets/Code-lists/master/UnifiedViews/skosified/currencies/currency.ttl, I see "Root scheme" with each concept. Should this be "Root concept"?
![image](https://cloud.githubusercontent.com/assets/718827/13487361/9610721e-e119-11e5-9e28-b777a2f988c1.png)

**Comment by jirihelmich** [comment]
Well, currently, it shows this badge for concepts that has no outgoing links. Which is not correct for all the possible scenarios. Is this event a good feature to have?

**Comment by jakubklimek** [comment]
OK, then remove it.
