### ISSUE TITLE
Homescreen: Usage examples display wrong

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#31]
![image](https://cloud.githubusercontent.com/assets/718827/13539049/271ab6c2-e24e-11e5-8075-504e29c3f57b.png)

**Comment by jirihelmich** [comment]
That's an issue of the underlying library, I need to solve it, but I don't know how. If you click into the fi... hm, automatic focus.

**Comment by jakubklimek** [comment]
I see... ok

**Comment by jakubklimek** [comment]
![image](https://cloud.githubusercontent.com/assets/718827/13661995/80ce0672-e697-11e5-8620-602e6e3c9f01.png)

**Comment by jirihelmich** [comment]
What should I see in the screenshot?

**Comment by jirihelmich** [comment]
Oh, I see.

**Comment by jirihelmich** [comment]
Works locally, I saw it on demo, will investigate from a faster connection.
