### ISSUE TITLE
DCV viz: Labels in visualization not dereferencing

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#41]
Viz: http://demo.visualization.linkedpipes.com/visualize/datacube#/id/77?view=chart&chartType=line&isPolar=false&language=cs&p=161b28c65a0ec4fe5f5d552a243c129f

![image](https://cloud.githubusercontent.com/assets/718827/13600224/cff219a8-e527-11e5-9f98-e17cf64e2752.png)

**Comment by jirihelmich** [comment]
Is it dereferenced inthe value selection? Or not even there?

**Comment by jirihelmich** [comment]
It's dereferenced OK, there is some problem with displaying labels in the legend. Will fix tomorrow.
