### ISSUE TITLE
Homescreen: Examples: Add icon for expected viz type

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#45]
Add an icon representing the expected visualization type to examples (between the button and the text preferrably)
- Cube: <a href="https://design.google.com/icons/#ic_multiline_chart">multiline_chart</a>
- Map: <a href="https://design.google.com/icons/#ic_place">place</a>
- Hierarchy: <a href="https://design.google.com/icons/#ic_format_list_bulleted">format_list_bulleted</a> (or something better?)

**Comment by jirihelmich** [comment]
And what for those that do not have a single visualisation as a result. E.g. LOD.cz.

**Comment by jakubklimek** [comment]
https://design.google.com/icons/#ic_view_carousel ?

**Comment by jakubklimek** [comment]
Or maybe https://design.google.com/icons/#ic_collections ... see which one is better

**Comment by jirihelmich** [comment]
I used icons available in my iconset, which is an older version. We can update it once I migrate to LP.
