### ISSUE TITLE
Map clustering broken

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#51]
![image](https://cloud.githubusercontent.com/assets/718827/15572243/a8b032de-233f-11e6-89d1-ffa9cd0de2a1.png)
- add option to disable clustering. Now it can be done via URL, so it should be doable in the menu as well.

**Comment by jirihelmich** [comment]
Someone from Google deleted the underlying PNG images from their repo. Those are hardcoded in the Clusterer JS. I will try to override and find suitable replacement. Also @tobice should notice this issue.

**Comment by tobice** [comment]
I was aware of this problem and kind of hoping that it was just a temporary problem that would just fix itself over time. I assume we're not the only one using this plugin, so someone might have solved it for us...

**Comment by jirihelmich** [comment]
Should be resolved by https://github.com/googlemaps/js-marker-clusterer/pull/72/commits/cb2ead36604b2a244f63ae09b48e77452eceb901
